//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFileManager.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebFileManager.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File &quot;{0}&quot; has been removed.
        /// </summary>
        internal static string FileHasBeenRemoved {
            get {
                return ResourceManager.GetString("FileHasBeenRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File has been renamed (oldName: {0}, newName: {1}).
        /// </summary>
        internal static string FileHasBeenRenamed {
            get {
                return ResourceManager.GetString("FileHasBeenRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File {0} has been upload.
        /// </summary>
        internal static string FileHasBeenUploaded {
            get {
                return ResourceManager.GetString("FileHasBeenUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Files have been removed.
        /// </summary>
        internal static string FilesHaveBeenRemoved {
            get {
                return ResourceManager.GetString("FilesHaveBeenRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Files have been resized.
        /// </summary>
        internal static string FilesHaveBeenResized {
            get {
                return ResourceManager.GetString("FilesHaveBeenResized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder &quot;{0}&quot; has been created.
        /// </summary>
        internal static string FolderHasBeenCreated {
            get {
                return ResourceManager.GetString("FolderHasBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder &quot;{0}&quot; has been removed.
        /// </summary>
        internal static string FolderHasBeenRemoved {
            get {
                return ResourceManager.GetString("FolderHasBeenRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder has been renamed (oldName: {0}, newName: {1}).
        /// </summary>
        internal static string FolderHasBeenRenamed {
            get {
                return ResourceManager.GetString("FolderHasBeenRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folders have been removed.
        /// </summary>
        internal static string FoldersHaveBeenRemoved {
            get {
                return ResourceManager.GetString("FoldersHaveBeenRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read only state has been changed (fileName: {0}, readOnly: {1}).
        /// </summary>
        internal static string ReadOnlyStateHasBeenChanged {
            get {
                return ResourceManager.GetString("ReadOnlyStateHasBeenChanged", resourceCulture);
            }
        }
    }
}
